Added DeviceAuth and ExchangeAuth
iXyles/fortnite-basic-api pull request #23
Opened 2020-03-22 14:48 UTC by ThisNils

Added methods to login using ExchangeAuth and DeviceAuth. This bypasses the captcha invalid error. Data of both can be provided in an async function eg to get it from a database

2020-03-22 17:17 UTC, iXyles requested changes
Except for comments, the code need to follow the rules set by .eslintrc.js with eslint.

2020-03-22 17:17 UTC, iXyles commented on example-test/index.js
> +  deviceAuth: () => JSON.parse(fs.readFileSync('./deviceauth.json', 'utf-8')),
Should be an async function...

2020-03-22 17:17 UTC, iXyles commented on example-test/index.js
> +  client.authenticator.on('device_auth_created', d => fs.writeFileSync('./deviceauth.json', JSON.stringify(d)));
Same goes here for async

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
> +    let token;
So why is this on a unique line? token is still only set once.

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
> +    console.log(deviceAuthDetails);
logger should not be in the code

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
> +  async createDeviceAuth() {
Missing comments

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
> +  async deleteAllDeviceAuths(dontDeleteIds = []) {
Missing comments

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
>    async login() {
Comment needs to be re-phrased.

2020-03-22 17:17 UTC, iXyles commented on src/Client/Authenticator.js
> +    console.log(this.entitlements)
logger should not be in code.

2020-03-22 17:18 UTC, iXyles commented on example-test/index.js
> +  deviceAuth: () => JSON.parse(fs.readFileSync('./deviceauth.json', 'utf-8')),
Also, why remove the example code that was there previously?

2020-03-22 22:31 UTC, modvili commented on src/Client/Authenticator.js
> +          await console.info(await this.killCurrentSession());
This await has no effect and can be removed.

2020-03-25 21:21 UTC, iXyles commented
Based a new branch of commit '162b136' and it is now merge into the master. Closing this PR since it is already in the master.

2020-03-25 21:21 UTC, closed without merging